package com.aurora.devopsagent.Domain.Enums;

public enum AuditActionType {
    INCIDENT_CREATED,
    CONTEXT_BUILD_STARTED,
    CONTEXT_BUILD_COMPLETED,
    CONTEXT_BUILD_FAILED,
    RULE_APPLIED,
    RCA_STARTED,
    RCA_ANALYSIS_STARTED,
    RCA_ANALYSIS_COMPLETED,
    RCA_ANALYSIS_FAILED,
    RECOMMENDATION_GENERATED,
    PR_OPENED,
    APPROVAL_REQUESTED,
    APPROVAL_GRANTED,
    APPROVAL_REJECTED,
    INCIDENT_ESCALATED,
    ESCALATED,
    ACTION_EXECUTED,
    ACTION_VERIFIED,
    ACTION_VERIFICATION_FAILED,
    ACTION_ROLLBACK_EXECUTED,
    RULE_PROMOTED,
    RULE_REJECTED,
    SELF_CONFIG_UPDATED,
    KNOWLEDGE_ENTRY_CREATED,
    KNOWLEDGE_ENTRY_REJECTED
}

