<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>22883215-7ab8-4052-b821-19dd390b4aef</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Protobuf Include="../../../protos/iam_tenant.proto" GrpcServices="Server" />
    <Protobuf Include="../../../protos/auth.proto" GrpcServices="Server" />
    <Protobuf Include="../../../protos/common.proto" GrpcServices="None" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.CognitoIdentityProvider" Version="4.0.10.1" />
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="3.7.7" />
    <PackageReference Include="Grpc.AspNetCore" Version="2.64.0" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\shared\shared.csproj" />
  </ItemGroup>

</Project>
