<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <!-- gRPC client stubs + packages đến từ BuildingBlocks.BFF (nơi duy nhất include Protobuf) -->
  <ItemGroup>
    <ProjectReference Include="..\BuildingBlocks.BFF\BuildingBlocks.BFF.csproj" />
  </ItemGroup>

</Project>
