// <auto-generated />
using System;
using IamTenant.Infrastructure.Persistences;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IamTenant.Infrastructure.Persistences.Migrations
{
    [DbContext(typeof(IamTenantDbContext))]
    partial class IamTenantDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IamTenant.Domain.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("IamTenant.Domain.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages");
                });

            modelBuilder.Entity("IamTenant.Domain.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f2abfd09-091f-44ee-4d13-8b2cc475a24c"),
                            Code = "ocr:create",
                            Description = "Allows create operation on ocr",
                            Module = "ocr"
                        },
                        new
                        {
                            Id = new Guid("0dbd7403-68e6-a892-6469-df2e70e1e833"),
                            Code = "ocr:read",
                            Description = "Allows read operation on ocr",
                            Module = "ocr"
                        },
                        new
                        {
                            Id = new Guid("d7cdfd4d-50d3-e907-75ca-f015a389027d"),
                            Code = "ocr:update",
                            Description = "Allows update operation on ocr",
                            Module = "ocr"
                        },
                        new
                        {
                            Id = new Guid("d46f3cb3-ead7-3d89-41e7-a619d5739ca5"),
                            Code = "ocr:delete",
                            Description = "Allows delete operation on ocr",
                            Module = "ocr"
                        },
                        new
                        {
                            Id = new Guid("f217e581-9e02-462f-61cd-55111753ebb8"),
                            Code = "ocr:import",
                            Description = "Allows import operation on ocr",
                            Module = "ocr"
                        },
                        new
                        {
                            Id = new Guid("8beabe90-8210-25ac-c7b0-f3827de23154"),
                            Code = "ocr:export",
                            Description = "Allows export operation on ocr",
                            Module = "ocr"
                        },
                        new
                        {
                            Id = new Guid("4fac1c69-8449-ac46-7950-02a1bbbccc28"),
                            Code = "ocr:assign",
                            Description = "Allows assign operation on ocr",
                            Module = "ocr"
                        },
                        new
                        {
                            Id = new Guid("f01a710f-a4e0-948b-e200-cc6e8de105b7"),
                            Code = "documents:create",
                            Description = "Allows create operation on documents",
                            Module = "documents"
                        },
                        new
                        {
                            Id = new Guid("857b24df-0d1b-73fe-7f78-3d6a32f5d243"),
                            Code = "documents:read",
                            Description = "Allows read operation on documents",
                            Module = "documents"
                        },
                        new
                        {
                            Id = new Guid("31d1e9ec-14cc-f2dd-a7c9-5d7a46fb7178"),
                            Code = "documents:update",
                            Description = "Allows update operation on documents",
                            Module = "documents"
                        },
                        new
                        {
                            Id = new Guid("ce7ce257-1af7-5e19-6204-0e627f666d39"),
                            Code = "documents:delete",
                            Description = "Allows delete operation on documents",
                            Module = "documents"
                        },
                        new
                        {
                            Id = new Guid("1c8018e6-7b49-9272-7205-62a82f3e3c40"),
                            Code = "documents:import",
                            Description = "Allows import operation on documents",
                            Module = "documents"
                        },
                        new
                        {
                            Id = new Guid("75dfde55-3ca2-ebfd-9f0b-d97976653e2e"),
                            Code = "documents:export",
                            Description = "Allows export operation on documents",
                            Module = "documents"
                        },
                        new
                        {
                            Id = new Guid("be875c50-f686-d8a4-ae8e-b21093e76d44"),
                            Code = "documents:assign",
                            Description = "Allows assign operation on documents",
                            Module = "documents"
                        },
                        new
                        {
                            Id = new Guid("9074e07d-5b60-86c6-0b76-c7767c00b9df"),
                            Code = "compliance:create",
                            Description = "Allows create operation on compliance",
                            Module = "compliance"
                        },
                        new
                        {
                            Id = new Guid("7fe854ea-7721-4bae-b0ef-e89b33e616f7"),
                            Code = "compliance:read",
                            Description = "Allows read operation on compliance",
                            Module = "compliance"
                        },
                        new
                        {
                            Id = new Guid("9f3754a7-9870-42d3-78ed-fcb514dbd427"),
                            Code = "compliance:update",
                            Description = "Allows update operation on compliance",
                            Module = "compliance"
                        },
                        new
                        {
                            Id = new Guid("187716d8-3c74-0e02-747e-02e1615e2866"),
                            Code = "compliance:delete",
                            Description = "Allows delete operation on compliance",
                            Module = "compliance"
                        },
                        new
                        {
                            Id = new Guid("faf272e6-dfdc-1357-6441-aeeb60df6874"),
                            Code = "compliance:import",
                            Description = "Allows import operation on compliance",
                            Module = "compliance"
                        },
                        new
                        {
                            Id = new Guid("8dc72112-1039-3cfe-b05a-c79bd13a8225"),
                            Code = "compliance:export",
                            Description = "Allows export operation on compliance",
                            Module = "compliance"
                        },
                        new
                        {
                            Id = new Guid("c410e9fe-f15d-ffe1-dc9a-e6b12fe8dd85"),
                            Code = "compliance:assign",
                            Description = "Allows assign operation on compliance",
                            Module = "compliance"
                        },
                        new
                        {
                            Id = new Guid("1e712188-2f5a-dd70-6f50-ac0a66320d32"),
                            Code = "negotiation:create",
                            Description = "Allows create operation on negotiation",
                            Module = "negotiation"
                        },
                        new
                        {
                            Id = new Guid("e6b052c0-458c-279e-fc41-5483ceac1bc0"),
                            Code = "negotiation:read",
                            Description = "Allows read operation on negotiation",
                            Module = "negotiation"
                        },
                        new
                        {
                            Id = new Guid("f7d47ebe-9ca0-826b-cf43-3a55abc0df6c"),
                            Code = "negotiation:update",
                            Description = "Allows update operation on negotiation",
                            Module = "negotiation"
                        },
                        new
                        {
                            Id = new Guid("42417a0a-4563-a7c4-c2ef-347d7334faf9"),
                            Code = "negotiation:delete",
                            Description = "Allows delete operation on negotiation",
                            Module = "negotiation"
                        },
                        new
                        {
                            Id = new Guid("c7f952a0-8420-7897-dde0-8dee648bba12"),
                            Code = "negotiation:import",
                            Description = "Allows import operation on negotiation",
                            Module = "negotiation"
                        },
                        new
                        {
                            Id = new Guid("e76d628b-4d81-0d8f-6f33-c1bd95c06d73"),
                            Code = "negotiation:export",
                            Description = "Allows export operation on negotiation",
                            Module = "negotiation"
                        },
                        new
                        {
                            Id = new Guid("5852a524-2a93-1166-f085-abac92302476"),
                            Code = "negotiation:assign",
                            Description = "Allows assign operation on negotiation",
                            Module = "negotiation"
                        },
                        new
                        {
                            Id = new Guid("e1f632dd-cfb6-9fd5-2447-3c14abab995b"),
                            Code = "customer_assistant:create",
                            Description = "Allows create operation on customer_assistant",
                            Module = "customer_assistant"
                        },
                        new
                        {
                            Id = new Guid("068e32ca-33e5-70a5-6604-c194694bc1e3"),
                            Code = "customer_assistant:read",
                            Description = "Allows read operation on customer_assistant",
                            Module = "customer_assistant"
                        },
                        new
                        {
                            Id = new Guid("7b8b7102-317b-4f4b-70fd-55709da64424"),
                            Code = "customer_assistant:update",
                            Description = "Allows update operation on customer_assistant",
                            Module = "customer_assistant"
                        },
                        new
                        {
                            Id = new Guid("754fb2cc-eba6-b8a2-6c94-373511245170"),
                            Code = "customer_assistant:delete",
                            Description = "Allows delete operation on customer_assistant",
                            Module = "customer_assistant"
                        },
                        new
                        {
                            Id = new Guid("734a0a4e-985c-ac75-21c0-5a337882e175"),
                            Code = "customer_assistant:import",
                            Description = "Allows import operation on customer_assistant",
                            Module = "customer_assistant"
                        },
                        new
                        {
                            Id = new Guid("cc867d6c-139d-d0e2-e1a8-35f8c4f0ed09"),
                            Code = "customer_assistant:export",
                            Description = "Allows export operation on customer_assistant",
                            Module = "customer_assistant"
                        },
                        new
                        {
                            Id = new Guid("15625c6c-9b22-c1ae-6983-4251cb40be02"),
                            Code = "customer_assistant:assign",
                            Description = "Allows assign operation on customer_assistant",
                            Module = "customer_assistant"
                        },
                        new
                        {
                            Id = new Guid("5c27a6c3-737a-b19d-8ab9-e0dc98c15200"),
                            Code = "iam:create",
                            Description = "Allows create operation on iam",
                            Module = "iam"
                        },
                        new
                        {
                            Id = new Guid("15b7ea39-f96f-729d-a8f0-9ab100a70f9d"),
                            Code = "iam:read",
                            Description = "Allows read operation on iam",
                            Module = "iam"
                        },
                        new
                        {
                            Id = new Guid("eac60635-7bf8-3672-09d5-8741b0d59532"),
                            Code = "iam:update",
                            Description = "Allows update operation on iam",
                            Module = "iam"
                        },
                        new
                        {
                            Id = new Guid("71a58738-ef23-26c2-6c4b-041d371e2427"),
                            Code = "iam:delete",
                            Description = "Allows delete operation on iam",
                            Module = "iam"
                        },
                        new
                        {
                            Id = new Guid("5a4cbf72-f6ad-9cef-3175-8c428c98d471"),
                            Code = "iam:import",
                            Description = "Allows import operation on iam",
                            Module = "iam"
                        },
                        new
                        {
                            Id = new Guid("2ed631a4-5ed7-f20b-90d5-4672f613bb3b"),
                            Code = "iam:export",
                            Description = "Allows export operation on iam",
                            Module = "iam"
                        },
                        new
                        {
                            Id = new Guid("5269576b-1b7c-0564-5877-6be5b44805ea"),
                            Code = "iam:assign",
                            Description = "Allows assign operation on iam",
                            Module = "iam"
                        },
                        new
                        {
                            Id = new Guid("81270dd0-8652-46a4-5298-80fe31302b99"),
                            Code = "route_planning:create",
                            Description = "Allows create operation on route_planning",
                            Module = "route_planning"
                        },
                        new
                        {
                            Id = new Guid("bd28c899-6437-ba29-33c3-a59ff4c79742"),
                            Code = "route_planning:read",
                            Description = "Allows read operation on route_planning",
                            Module = "route_planning"
                        },
                        new
                        {
                            Id = new Guid("9a1074c4-b162-26e0-bf4c-cd688f9e1c7c"),
                            Code = "route_planning:update",
                            Description = "Allows update operation on route_planning",
                            Module = "route_planning"
                        },
                        new
                        {
                            Id = new Guid("e7ecab79-93ce-0d34-affe-1c2a77e4405c"),
                            Code = "route_planning:delete",
                            Description = "Allows delete operation on route_planning",
                            Module = "route_planning"
                        },
                        new
                        {
                            Id = new Guid("b25b0111-2e88-6ba7-34ba-5a771dec7241"),
                            Code = "route_planning:import",
                            Description = "Allows import operation on route_planning",
                            Module = "route_planning"
                        },
                        new
                        {
                            Id = new Guid("e099cee0-e184-1ade-aafb-c89ee21e2ba3"),
                            Code = "route_planning:export",
                            Description = "Allows export operation on route_planning",
                            Module = "route_planning"
                        },
                        new
                        {
                            Id = new Guid("83602fc0-e37d-f93a-d8d0-3aac458e5f1a"),
                            Code = "route_planning:assign",
                            Description = "Allows assign operation on route_planning",
                            Module = "route_planning"
                        },
                        new
                        {
                            Id = new Guid("6fc2d4ff-4899-517b-38c7-2d72128b1624"),
                            Code = "financial_tax:create",
                            Description = "Allows create operation on financial_tax",
                            Module = "financial_tax"
                        },
                        new
                        {
                            Id = new Guid("b89eae95-03b7-82fa-270f-6f5133454213"),
                            Code = "financial_tax:read",
                            Description = "Allows read operation on financial_tax",
                            Module = "financial_tax"
                        },
                        new
                        {
                            Id = new Guid("081e77ae-7147-2809-2f39-e9b9cb280902"),
                            Code = "financial_tax:update",
                            Description = "Allows update operation on financial_tax",
                            Module = "financial_tax"
                        },
                        new
                        {
                            Id = new Guid("db360faa-461c-58e7-4d7d-b5f804e248c2"),
                            Code = "financial_tax:delete",
                            Description = "Allows delete operation on financial_tax",
                            Module = "financial_tax"
                        },
                        new
                        {
                            Id = new Guid("d5fca949-8ce0-187a-0f18-4bffc54af9fa"),
                            Code = "financial_tax:import",
                            Description = "Allows import operation on financial_tax",
                            Module = "financial_tax"
                        },
                        new
                        {
                            Id = new Guid("2cfedbf2-c0ae-3639-54a0-56a8179d0bcc"),
                            Code = "financial_tax:export",
                            Description = "Allows export operation on financial_tax",
                            Module = "financial_tax"
                        },
                        new
                        {
                            Id = new Guid("5a7eb9f6-3de5-db44-3b3a-cafde0e300aa"),
                            Code = "financial_tax:assign",
                            Description = "Allows assign operation on financial_tax",
                            Module = "financial_tax"
                        },
                        new
                        {
                            Id = new Guid("19857379-200c-97d0-5ff9-6f0b9badda77"),
                            Code = "gps_tracking:create",
                            Description = "Allows create operation on gps_tracking",
                            Module = "gps_tracking"
                        },
                        new
                        {
                            Id = new Guid("faa8cf4e-c7aa-d9a2-82e6-8cf44cfc27da"),
                            Code = "gps_tracking:read",
                            Description = "Allows read operation on gps_tracking",
                            Module = "gps_tracking"
                        },
                        new
                        {
                            Id = new Guid("590cd177-2903-543a-2ccc-c2fa3e8139f1"),
                            Code = "gps_tracking:update",
                            Description = "Allows update operation on gps_tracking",
                            Module = "gps_tracking"
                        },
                        new
                        {
                            Id = new Guid("3d0ae68a-a252-8a70-af99-411d4e24da5e"),
                            Code = "gps_tracking:delete",
                            Description = "Allows delete operation on gps_tracking",
                            Module = "gps_tracking"
                        },
                        new
                        {
                            Id = new Guid("71d5a7d6-7606-14a6-6ad1-1e8f02f0e104"),
                            Code = "gps_tracking:import",
                            Description = "Allows import operation on gps_tracking",
                            Module = "gps_tracking"
                        },
                        new
                        {
                            Id = new Guid("a9243615-16e0-02f0-5c76-d82e58a9b9f9"),
                            Code = "gps_tracking:export",
                            Description = "Allows export operation on gps_tracking",
                            Module = "gps_tracking"
                        },
                        new
                        {
                            Id = new Guid("c042d5aa-947e-76f7-2cc0-4babb6d75b4e"),
                            Code = "gps_tracking:assign",
                            Description = "Allows assign operation on gps_tracking",
                            Module = "gps_tracking"
                        },
                        new
                        {
                            Id = new Guid("9746829c-f3f6-b3b0-d5b6-ac14c7dbb8fa"),
                            Code = "billing_settlement:create",
                            Description = "Allows create operation on billing_settlement",
                            Module = "billing_settlement"
                        },
                        new
                        {
                            Id = new Guid("f2a3cb70-fd5d-c6d0-2433-f42f51964b27"),
                            Code = "billing_settlement:read",
                            Description = "Allows read operation on billing_settlement",
                            Module = "billing_settlement"
                        },
                        new
                        {
                            Id = new Guid("6081e667-ca38-9248-3fbd-bb64e16673ef"),
                            Code = "billing_settlement:update",
                            Description = "Allows update operation on billing_settlement",
                            Module = "billing_settlement"
                        },
                        new
                        {
                            Id = new Guid("1ff37fd5-4256-1381-f7d1-00ecd272c99e"),
                            Code = "billing_settlement:delete",
                            Description = "Allows delete operation on billing_settlement",
                            Module = "billing_settlement"
                        },
                        new
                        {
                            Id = new Guid("645c65e3-9165-2bc5-10fa-aa6d110989ec"),
                            Code = "billing_settlement:import",
                            Description = "Allows import operation on billing_settlement",
                            Module = "billing_settlement"
                        },
                        new
                        {
                            Id = new Guid("1c3ca6c8-4329-e474-b556-57f0038debf8"),
                            Code = "billing_settlement:export",
                            Description = "Allows export operation on billing_settlement",
                            Module = "billing_settlement"
                        },
                        new
                        {
                            Id = new Guid("e7537c5f-f67b-2c09-9997-eeb6e976f5f6"),
                            Code = "billing_settlement:assign",
                            Description = "Allows assign operation on billing_settlement",
                            Module = "billing_settlement"
                        });
                });

            modelBuilder.Entity("IamTenant.Domain.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Code = "SYSTEM_ADMIN",
                            CreatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsSystemRole = true,
                            Name = "System Administrator",
                            TenantId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Code = "TENANT_ADMIN",
                            CreatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsSystemRole = true,
                            Name = "Tenant Administrator",
                            TenantId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Code = "TENANT_STAFF",
                            CreatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsSystemRole = true,
                            Name = "Tenant Staff",
                            TenantId = new Guid("00000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("IamTenant.Domain.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("f2abfd09-091f-44ee-4d13-8b2cc475a24c")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("0dbd7403-68e6-a892-6469-df2e70e1e833")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("d7cdfd4d-50d3-e907-75ca-f015a389027d")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("d46f3cb3-ead7-3d89-41e7-a619d5739ca5")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("f217e581-9e02-462f-61cd-55111753ebb8")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("8beabe90-8210-25ac-c7b0-f3827de23154")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("4fac1c69-8449-ac46-7950-02a1bbbccc28")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("f01a710f-a4e0-948b-e200-cc6e8de105b7")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("857b24df-0d1b-73fe-7f78-3d6a32f5d243")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("31d1e9ec-14cc-f2dd-a7c9-5d7a46fb7178")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("ce7ce257-1af7-5e19-6204-0e627f666d39")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("1c8018e6-7b49-9272-7205-62a82f3e3c40")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("75dfde55-3ca2-ebfd-9f0b-d97976653e2e")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("be875c50-f686-d8a4-ae8e-b21093e76d44")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("9074e07d-5b60-86c6-0b76-c7767c00b9df")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("7fe854ea-7721-4bae-b0ef-e89b33e616f7")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("9f3754a7-9870-42d3-78ed-fcb514dbd427")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("187716d8-3c74-0e02-747e-02e1615e2866")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("faf272e6-dfdc-1357-6441-aeeb60df6874")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("8dc72112-1039-3cfe-b05a-c79bd13a8225")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("c410e9fe-f15d-ffe1-dc9a-e6b12fe8dd85")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("1e712188-2f5a-dd70-6f50-ac0a66320d32")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("e6b052c0-458c-279e-fc41-5483ceac1bc0")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("f7d47ebe-9ca0-826b-cf43-3a55abc0df6c")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("42417a0a-4563-a7c4-c2ef-347d7334faf9")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("c7f952a0-8420-7897-dde0-8dee648bba12")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("e76d628b-4d81-0d8f-6f33-c1bd95c06d73")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("5852a524-2a93-1166-f085-abac92302476")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("e1f632dd-cfb6-9fd5-2447-3c14abab995b")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("068e32ca-33e5-70a5-6604-c194694bc1e3")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("7b8b7102-317b-4f4b-70fd-55709da64424")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("754fb2cc-eba6-b8a2-6c94-373511245170")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("734a0a4e-985c-ac75-21c0-5a337882e175")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("cc867d6c-139d-d0e2-e1a8-35f8c4f0ed09")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("15625c6c-9b22-c1ae-6983-4251cb40be02")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("5c27a6c3-737a-b19d-8ab9-e0dc98c15200")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("15b7ea39-f96f-729d-a8f0-9ab100a70f9d")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("eac60635-7bf8-3672-09d5-8741b0d59532")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("71a58738-ef23-26c2-6c4b-041d371e2427")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("5a4cbf72-f6ad-9cef-3175-8c428c98d471")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("2ed631a4-5ed7-f20b-90d5-4672f613bb3b")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("5269576b-1b7c-0564-5877-6be5b44805ea")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("81270dd0-8652-46a4-5298-80fe31302b99")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("bd28c899-6437-ba29-33c3-a59ff4c79742")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("9a1074c4-b162-26e0-bf4c-cd688f9e1c7c")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("e7ecab79-93ce-0d34-affe-1c2a77e4405c")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("b25b0111-2e88-6ba7-34ba-5a771dec7241")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("e099cee0-e184-1ade-aafb-c89ee21e2ba3")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("83602fc0-e37d-f93a-d8d0-3aac458e5f1a")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("6fc2d4ff-4899-517b-38c7-2d72128b1624")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("b89eae95-03b7-82fa-270f-6f5133454213")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("081e77ae-7147-2809-2f39-e9b9cb280902")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("db360faa-461c-58e7-4d7d-b5f804e248c2")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("d5fca949-8ce0-187a-0f18-4bffc54af9fa")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("2cfedbf2-c0ae-3639-54a0-56a8179d0bcc")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("5a7eb9f6-3de5-db44-3b3a-cafde0e300aa")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("19857379-200c-97d0-5ff9-6f0b9badda77")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("faa8cf4e-c7aa-d9a2-82e6-8cf44cfc27da")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("590cd177-2903-543a-2ccc-c2fa3e8139f1")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("3d0ae68a-a252-8a70-af99-411d4e24da5e")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("71d5a7d6-7606-14a6-6ad1-1e8f02f0e104")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("a9243615-16e0-02f0-5c76-d82e58a9b9f9")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("c042d5aa-947e-76f7-2cc0-4babb6d75b4e")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("9746829c-f3f6-b3b0-d5b6-ac14c7dbb8fa")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("f2a3cb70-fd5d-c6d0-2433-f42f51964b27")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("6081e667-ca38-9248-3fbd-bb64e16673ef")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("1ff37fd5-4256-1381-f7d1-00ecd272c99e")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("645c65e3-9165-2bc5-10fa-aa6d110989ec")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("1c3ca6c8-4329-e474-b556-57f0038debf8")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("e7537c5f-f67b-2c09-9997-eeb6e976f5f6")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("5c27a6c3-737a-b19d-8ab9-e0dc98c15200")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("15b7ea39-f96f-729d-a8f0-9ab100a70f9d")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("eac60635-7bf8-3672-09d5-8741b0d59532")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("71a58738-ef23-26c2-6c4b-041d371e2427")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("5a4cbf72-f6ad-9cef-3175-8c428c98d471")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("2ed631a4-5ed7-f20b-90d5-4672f613bb3b")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("5269576b-1b7c-0564-5877-6be5b44805ea")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("81270dd0-8652-46a4-5298-80fe31302b99")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("bd28c899-6437-ba29-33c3-a59ff4c79742")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("9a1074c4-b162-26e0-bf4c-cd688f9e1c7c")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("e7ecab79-93ce-0d34-affe-1c2a77e4405c")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("b25b0111-2e88-6ba7-34ba-5a771dec7241")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("e099cee0-e184-1ade-aafb-c89ee21e2ba3")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("83602fc0-e37d-f93a-d8d0-3aac458e5f1a")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("0dbd7403-68e6-a892-6469-df2e70e1e833")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("8beabe90-8210-25ac-c7b0-f3827de23154")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("f217e581-9e02-462f-61cd-55111753ebb8")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("857b24df-0d1b-73fe-7f78-3d6a32f5d243")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("75dfde55-3ca2-ebfd-9f0b-d97976653e2e")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("1c8018e6-7b49-9272-7205-62a82f3e3c40")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("7fe854ea-7721-4bae-b0ef-e89b33e616f7")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("8dc72112-1039-3cfe-b05a-c79bd13a8225")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("faf272e6-dfdc-1357-6441-aeeb60df6874")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("e6b052c0-458c-279e-fc41-5483ceac1bc0")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("e76d628b-4d81-0d8f-6f33-c1bd95c06d73")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("c7f952a0-8420-7897-dde0-8dee648bba12")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("068e32ca-33e5-70a5-6604-c194694bc1e3")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("cc867d6c-139d-d0e2-e1a8-35f8c4f0ed09")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("734a0a4e-985c-ac75-21c0-5a337882e175")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("15b7ea39-f96f-729d-a8f0-9ab100a70f9d")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("2ed631a4-5ed7-f20b-90d5-4672f613bb3b")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("5a4cbf72-f6ad-9cef-3175-8c428c98d471")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("bd28c899-6437-ba29-33c3-a59ff4c79742")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("e099cee0-e184-1ade-aafb-c89ee21e2ba3")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("b25b0111-2e88-6ba7-34ba-5a771dec7241")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("b89eae95-03b7-82fa-270f-6f5133454213")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("2cfedbf2-c0ae-3639-54a0-56a8179d0bcc")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("d5fca949-8ce0-187a-0f18-4bffc54af9fa")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("faa8cf4e-c7aa-d9a2-82e6-8cf44cfc27da")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("a9243615-16e0-02f0-5c76-d82e58a9b9f9")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("71d5a7d6-7606-14a6-6ad1-1e8f02f0e104")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("f2a3cb70-fd5d-c6d0-2433-f42f51964b27")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("1c3ca6c8-4329-e474-b556-57f0038debf8")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("645c65e3-9165-2bc5-10fa-aa6d110989ec")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("81270dd0-8652-46a4-5298-80fe31302b99")
                        });
                });

            modelBuilder.Entity("IamTenant.Domain.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CompanyDomain")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PlanType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TaxCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CompanyDomain")
                        .IsUnique();

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("IamTenant.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CognitoSub")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PermissionVersion")
                        .HasColumnType("integer");

                    b.Property<string>("StaffCode")
                        .HasColumnType("text");

                    b.Property<int>("StaffType")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<int>("UserType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CognitoSub")
                        .IsUnique();

                    b.HasIndex("TenantId", "CreatedAt");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique();

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("IamTenant.Domain.UserPermission", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("UserPermissions");
                });

            modelBuilder.Entity("IamTenant.Domain.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("IamTenant.Domain.Role", b =>
                {
                    b.HasOne("IamTenant.Domain.Tenant", "Tenant")
                        .WithMany("Roles")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("IamTenant.Domain.RolePermission", b =>
                {
                    b.HasOne("IamTenant.Domain.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IamTenant.Domain.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("IamTenant.Domain.User", b =>
                {
                    b.HasOne("IamTenant.Domain.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("IamTenant.Domain.UserPermission", b =>
                {
                    b.HasOne("IamTenant.Domain.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IamTenant.Domain.User", "User")
                        .WithMany("UserPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IamTenant.Domain.UserRole", b =>
                {
                    b.HasOne("IamTenant.Domain.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IamTenant.Domain.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IamTenant.Domain.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("IamTenant.Domain.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("IamTenant.Domain.Tenant", b =>
                {
                    b.Navigation("Roles");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("IamTenant.Domain.User", b =>
                {
                    b.Navigation("UserPermissions");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
