export enum AssistantIntent {
  GENERAL = 'GENERAL',
  SHIPMENT_QUERY = 'SHIPMENT_QUERY',
  BILLING_QUERY = 'BILLING_QUERY',
  REGULATORY_QUERY = 'REGULATORY_QUERY',
  KNOWLEDGE_QUERY = 'KNOWLEDGE_QUERY',
  HYBRID_RAG_QUERY = 'HYBRID_RAG_QUERY',
  UNKNOWN = 'UNKNOWN',
}
