syntax = "proto3";

package audit;

import "google/protobuf/timestamp.proto";

option csharp_namespace = "Audit.Grpc";
option java_package = "com.aurora.audit.grpc";
option java_multiple_files = true;
  
service AuditLogService {
  // Method 1: Dành cho System / Dev / Platform Owner
  rpc GetSystemAuditLogs (GetSystemAuditLogsRequest) returns (AuditLogsResponse);

  // Method 2: Dành cho Admin / Tenant Admin
  rpc GetAdminAuditLogs (GetAdminAuditLogsRequest) returns (AuditLogsResponse);

  // Ingest Audit Event qua gRPC
  rpc IngestAuditEvent (IngestAuditEventRequest) returns (AuditLogMessage);
}

message GetSystemAuditLogsRequest {
  string serviceName = 1;
  string eventType = 2;
  int32 page = 3;
  int32 limit = 4;
  string tenantId = 5;
  string userId = 6;
}

message GetAdminAuditLogsRequest {
  string tenantId = 1;
  string userId = 2;
  int32 page = 3;
  int32 limit = 4;
}

message IngestAuditEventRequest {
  string eventId = 1;
  string serviceName = 2;
  string eventType = 3;
  string tenantId = 4;
  string userId = 5;
  string userRole = 6;
  string resourceId = 7;
  string payloadJson = 8;
  string ipAddress = 9;
}

message AuditLogMessage {
  string id = 1;
  string serviceName = 2;
  string eventType = 3;
  string tenantId = 4;
  string userId = 5;
  string userRole = 6;
  string resourceId = 7;
  string payloadJson = 8;
  string ipAddress = 9;
  google.protobuf.Timestamp createdAt = 10;
}

message AuditLogsResponse {
  repeated AuditLogMessage logs = 1;
  int32 page = 2;
  int32 limit = 3;
  int32 totalItems = 4;
  int32 totalPages = 5;
}
