nameOverride: "realtime-hub-service"
fullnameOverride: "realtime-hub-service"

image:
  repository: acrauroracoredemo.azurecr.io/aurora/realtime-hub-service
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5005
  targetPort: 5005
  name: http

env:
  NODE_ENV: "production"
  WEBSOCKET_PORT: "5005"
  PORT: "5005"
  REDIS_HOST: "redis-master.aurora.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_TLS: "false"
  RABBITMQ_HOST: "rabbitmq.aurora.svc.cluster.local"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USERNAME: "aurora_admin"

externalSecret:
  enabled: true
  secretStoreRef:
    name: azure-keyvault-store
    kind: ClusterSecretStore
  data:
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: redis-password
    - secretKey: RABBITMQ_PASSWORD
      remoteRef:
        key: rabbitmq-password


resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

serviceMonitor:
  enabled: true
  path: /metrics
  port: http

startupProbe:
  httpGet:
    path: /healthz/liveness
    port: http
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 36

livenessProbe:
  httpGet:
    path: /healthz/liveness
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /healthz/readiness
    port: http
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 6
