nameOverride: "iam-tenant"
fullnameOverride: "iam-tenant"

image:
  repository: acrauroracorekhoa.azurecr.io/aurora/iam-tenant
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000
  targetPort: 5000

env:
  ASPNETCORE_ENVIRONMENT: "Production"
  AWS_REGION: "ap-southeast-1"
  Redis__Host: "redis-master.aurora.svc.cluster.local:6379"
  Redis__Ssl: "false"
  Redis__AbortConnect: "false"
  RabbitMQ__Host: "rabbitmq.aurora.svc.cluster.local"
  RabbitMQ__Port: "5672"
  RabbitMQ__Username: "aurora_admin"

externalSecret:
  enabled: true
  secretStoreRef:
    name: azure-keyvault-store
    kind: ClusterSecretStore
  data:
    - secretKey: ConnectionStrings__DefaultConnection
      remoteRef:
        key: aurora-iam-db-connection
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: aws-access-key-id
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: aws-secret-access-key
    - secretKey: AWS_COGNITO_USER_POOL_ID
      remoteRef:
        key: aws-cognito-user-pool-id
    - secretKey: AWS_COGNITO_CLIENT_ID
      remoteRef:
        key: aws-cognito-client-id
    - secretKey: AWS_COGNITO_CLIENT_SECRET
      remoteRef:
        key: aws-cognito-client-secret
    - secretKey: Auth__Jwt__Audience
      remoteRef:  
        key: aws-cognito-client-id
    - secretKey: Redis__Password
      remoteRef:
        key: redis-password
    - secretKey: RabbitMQ__Password
      remoteRef:
        key: rabbitmq-password

resources:
  requests:
    cpu: 25m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

serviceMonitor:
  enabled: true
  path: /metrics
  port: http

startupProbe:
  httpGet: null
  tcpSocket:
    port: 5000
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 36

livenessProbe:
  httpGet: null
  tcpSocket:
    port: 5000
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 3

readinessProbe:
  httpGet: null
  tcpSocket:
    port: 5000
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 6

