nameOverride: "regulatory-compliance"
fullnameOverride: "regulatory-compliance"

image:
  repository: acrauroracoredemo.azurecr.io/aurora/regulatory-compliance
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000
  targetPort: 5000

env:
  ASPNETCORE_ENVIRONMENT: "Production"
  RabbitMQ__Host: "10.10.2.50" # Core Internal LoadBalancer over VNet Peering
  RabbitMQ__Port: "5672"
  RabbitMQ__Username: "aurora_admin"
  Redis__Host: "redis-aurora-shared-demo.southeastasia.redis.azure.net:10000"
  Redis__Ssl: "true"
  Redis__AbortConnect: "false"

externalSecret:
  enabled: true
  apiVersion: external-secrets.io/v1beta1
  secretStoreRef:
    name: azure-keyvault-store
    kind: ClusterSecretStore
  data:
    - secretKey: ConnectionStrings__DefaultConnection
      remoteRef:
        key: aurora-regulatory-compliance-db-connection
    - secretKey: RabbitMQ__Password
      remoteRef:
        key: rabbitmq-password
    - secretKey: Redis__Password
      remoteRef:
        key: redis-password

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

serviceMonitor:
  enabled: true
  path: /metrics
  port: http
