apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: aurora-ai-workloads
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/Aurora-Log/aurora-server.git
        revision: HEAD
        files:
          - path: "src/**/*/deploy/descriptor.yaml"
  template:
    metadata:
      name: "ai-{{logicalService}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/Aurora-Log/aurora-server.git
        targetRevision: HEAD
        path: infra/helm/{{deployment.chart}}
        helm:
          valueFiles:
            - "{{path.path}}/helm/{{deployment.values}}"
      destination:
        name: cluster-aks-ai
        namespace: "{{deployment.namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - SkipDryRunOnMissingResource=true
