package com.aurora.devopsagent.Application.Services;

import com.aurora.devopsagent.Domain.Entity.Incident;
import com.aurora.devopsagent.Domain.Entity.PendingRule;
import com.aurora.devopsagent.Domain.Entity.RcaAnalysis;
import com.aurora.devopsagent.Domain.Enums.AuditActionType;
import com.aurora.devopsagent.Infrastructure.AI.AiGovernanceClient;
import com.aurora.devopsagent.Infrastructure.Audit.AuditEventOutboxService;
import com.aurora.devopsagent.Infrastructure.Persistence.PendingRuleJpaRepository;
import com.aurora.devopsagent.Infrastructure.Security.RedactionService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.Map;

/**
 * RuleProposalService: Generates new remediation rule proposals via AiGovernance
 * (capability = devops.rule_proposal) from resolved incidents.
 */
@Service
public class RuleProposalService {

    private static final Logger log = LoggerFactory.getLogger(RuleProposalService.class);
    private static final String RULE_PROPOSAL_CAPABILITY = "devops.rule_proposal";

    private final PendingRuleJpaRepository pendingRuleRepository;
    private final RedactionService redactionService;
    private final AiGovernanceClient aiGovernanceClient;
    private final AuditEventOutboxService outboxService;

    public RuleProposalService(
            PendingRuleJpaRepository pendingRuleRepository,
            RedactionService redactionService,
            AiGovernanceClient aiGovernanceClient,
            AuditEventOutboxService outboxService) {
        this.pendingRuleRepository = pendingRuleRepository;
        this.redactionService = redactionService;
        this.aiGovernanceClient = aiGovernanceClient;
        this.outboxService = outboxService;
    }

    @Transactional
    public PendingRule proposeRule(Incident incident, RcaAnalysis analysis) {
        String sanitizedSignature = redactionService.redact(incident.getErrorSignature());
        String sanitizedRca = redactionService.redact(incident.getRcaRecommendation());

        String prompt = String.format(
                """
                You are the Aurora Rule Proposer.
                Based on this resolved incident and RCA, suggest an automated remediation rule.

                - Affected Service: %s
                - Error Signature: %s
                - Root Cause: %s
                - Resolution Action: %s

                Format your proposed rule:
                RULE_NAME: <concise name>
                ACTION_TYPE: <RESTART_POD | CLEAR_CACHE | ADJUST_CONFIG | ROLLBACK_DEPLOYMENT>
                ACTION_PARAMS: <json parameters>
                """,
                incident.getAffectedService(),
                sanitizedSignature,
                incident.getRcaRootCause(),
                sanitizedRca
        );

        AiGovernanceClient.GenerateCommand command = new AiGovernanceClient.GenerateCommand(
                RULE_PROPOSAL_CAPABILITY,
                prompt,
                2000,
                800,
                Map.of("service", incident.getAffectedService() != null ? incident.getAffectedService() : "unknown")
        );

        AiGovernanceClient.GenerateResult result = aiGovernanceClient.generate(command);

        PendingRule pendingRule = new PendingRule();
        pendingRule.setProposedRuleName("AutoRule-" + incident.getAffectedService() + "-" + System.currentTimeMillis());
        pendingRule.setErrorPattern(incident.getErrorSignature());
        pendingRule.setActionType("RESTART_POD");
        pendingRule.setActionParamsJson(String.format("{\"reason\":\"Generated by AiGovernance %s\"}", result.decisionId()));
        pendingRule.setSourceIncidentId(incident.getId());
        pendingRule.setStatus("PENDING");
        pendingRule.setGovernanceDecisionId(result.decisionId());
        pendingRule.setAutomationLevel(result.automationLevel());
        pendingRule.setRequiresApproval(result.requiresApproval());

        PendingRule saved = pendingRuleRepository.save(pendingRule);

        outboxService.enqueue(
                incident.getCorrelationId(),
                incident.getId(),
                AuditActionType.RULE_APPLIED,
                String.format("{\"pendingRuleId\":\"%s\",\"decisionId\":\"%s\"}", saved.getId(), result.decisionId())
        );

        log.info("Proposed new rule id={} for incident id={}", saved.getId(), incident.getId());
        return saved;
    }
}
