apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rabbitmq-external-secret
  namespace: aurora
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: azure-keyvault-store
    kind: ClusterSecretStore

  target:
    name: rabbitmq-secret
    creationPolicy: Owner

  data:
    - secretKey: password
      remoteRef:
        key: rabbitmq-password