apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ingress
  labels:
    app.kubernetes.io/name: stalwart
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.ports.smtp.enabled }}
    - name: smtp
      port: 25
      targetPort: 25
      protocol: TCP
    {{- end }}
    {{- if .Values.ports.submission.enabled }}
    - name: submission
      port: 587
      targetPort: 587
      protocol: TCP
    {{- end }}
    {{- if .Values.ports.imaps.enabled }}
    - name: imaps
      port: 993
      targetPort: 993
      protocol: TCP
    {{- end }}
    - name: admin
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: stalwart
    app.kubernetes.io/instance: {{ .Release.Name }}
