apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-aurora-core
  namespace: aurora
  annotations:
    azure.workload.identity/client-id: "3ca35f49-0390-431f-839f-b26c541b69ea"
  labels:
    azure.workload.identity/use: "true"