{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "aurora-service.fullname" . }}-external-secret
  labels:
    {{- include "aurora-service.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ .Values.externalSecret.target.name | default (printf "%s-kv-secret" (include "aurora-service.fullname" .)) }}
    creationPolicy: {{ .Values.externalSecret.target.creationPolicy | default "Owner" }}
  data:
    {{- toYaml .Values.externalSecret.data | nindent 4 }}
{{- end }}
