apiVersion: v1
kind: Service
metadata:
  name: {{ include "aurora-service.fullname" . }}
  labels:
    {{- include "aurora-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default .Values.service.port }}
      protocol: {{ .Values.service.protocol | default "TCP" }}
      name: {{ .Values.service.name | default "http" }}
    {{- range .Values.additionalPorts }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort | default .containerPort | default .port }}
      protocol: {{ .protocol | default "TCP" }}
    {{- end }}
  selector:
    {{- include "aurora-service.selectorLabels" . | nindent 4 }}
