apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aurora-root-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Aurora-Log/aurora-server.git
    targetRevision: HEAD
    path: infra/argocd/applicationsets
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
